name: Daily Git Submodule Update

on:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 04:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensures submodules are initialized

      - name: Display Current Directory Structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files and folders:"
          ls -lah
        shell: bash

      - name: Update Git Submodules
        run: |
          echo "Starting submodule update..."
          git submodule sync --recursive || { echo "Submodule Sync failed!"; exit 1; }
          git submodule update --init --recursive || { echo "Submodule initialization failed!"; exit 1; }
          git submodule update --remote --merge || { echo "Submodule update failed!"; exit 1; }
          echo "Submodules updated successfully."
        shell: bash
        
      - name: Download Moodle version file
        run: |
          for i in {1..3}; do
            wget -q https://raw.githubusercontent.com/moodle/moodle/MOODLE_500_STABLE/version.php -O version.php && break
            echo "Download failed, retrying ($i/3)..."
            sleep 5
          done
          if [ ! -s version.php ]; then
            echo "Failed to download Moodle version file after 3 attempts"
            exit 1
          fi
        shell: bash
              
      - name: Push updated submodules
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi
          echo "Committing changes..."
          git commit -m "Automated submodule update"
          git push
        shell: bash
