name: Update Moodle Plugins Submodules

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 2 * * *' # Runs every day at 2:00 AM UTC (Optional)

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          # You must add this private key to your Repo Secrets
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git Identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          # Prevent SSH prompt hanging on unknown host
          mkdir -p ~/.ssh
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Execute Update Script
        env:
          FOLDERNAME: moodle500-plugins
        run: |
          echo "Clone git project..."
          git clone git@github.com:AdrianoRuseler/moodle500-plugins.git
          
          cd $FOLDERNAME
          
          # Initialize submodules
          git submodule update --init

          echo "Get version file.."
          wget https://raw.githubusercontent.com/moodle/moodle/MOODLE_500_STABLE/version.php -O version.php

          echo "Run: git submodule update --remote"
          git submodule update --remote

          # Check if there are changes before committing
          if [[ -n $(git status -s) ]]; then
            echo "Changes detected. Committing..."
            git add .
            git commit -m "GitHub Actions submodule update."
            
            # Push changes using the SSH key setup earlier
            git push origin HEAD
          else
            echo "No changes detected. Skipping commit."
          fi
          
